// SPDX-License-Identifier: GPL-3.0-or-later
// Act-Fancer — game top-level: wires main + sound + video + SDRAM bridge.
// This is the "core" module instantiated from the MiSTer emu wrapper
// (ActFancer.sv → emu module).
//
// Clock domain: clk = 21.477272 MHz (master XTAL). Generated by PLL upstream.

module actfancer_top
(
    input              clk,           // 21.477 MHz
    input              clk_sdram,     // SDRAM controller clock (same domain stubbed)
    input              rst,           // sync rst, active high
    input              pause,         // 1=freeze CPU/audio (joy[12] toggle)

    // Joystick / DIPs (positive logic from MiSTer; we invert to active-low internally)
    input        [7:0] joy1,          // {start1, ?, btn2, btn1, R, L, D, U} active-high
    input        [7:0] joy2,
    input        [7:0] coin,          // {?, ?, ?, ?, ?, service1, coin2, coin1}
    input       [15:0] dsw,

    // ROM download (passed through to SDRAM bridge in emu wrapper)
    input              ioctl_download,
    input       [24:0] ioctl_addr,
    input        [7:0] ioctl_dout,
    input              ioctl_wr,
    input       [15:0] ioctl_index,

    // SDRAM client read ports (cablati al bridge fuori, lato emu)
    output      [17:0] sdr_pf0_addr,
    output             sdr_pf0_cs,
    input       [31:0] sdr_pf0_data,
    input              sdr_pf0_ok,

    output      [17:0] sdr_pf1_addr,
    output             sdr_pf1_cs,
    input       [31:0] sdr_pf1_data,
    input              sdr_pf1_ok,

    output      [18:0] sdr_spr_addr,
    output             sdr_spr_cs,
    input       [31:0] sdr_spr_data,
    input              sdr_spr_ok,

    output      [17:0] sdr_oki_addr,
    output             sdr_oki_cs,
    input        [7:0] sdr_oki_data,
    input              sdr_oki_ok,

    // Video out
    output       [7:0] vga_r,
    output       [7:0] vga_g,
    output       [7:0] vga_b,
    output             vga_hs,
    output             vga_vs,
    output             vga_hb,
    output             vga_vb,
    output             ce_pix,

    // Audio out
    output signed [15:0] aud_l,
    output signed [15:0] aud_r,
    // Audio OSD volumi (Q4.4, 16=100%)
    input        [6:0] vol_opn,
    input        [6:0] vol_opl,
    input        [6:0] vol_oki,

    // OSD debug (3 layer × 12 bit + 3 enable)
    input              dbg_dis_pf0,
    input              dbg_dis_pf1,
    input              dbg_dis_spr,
    input       [11:0] dbg_pf0,
    input       [11:0] dbg_pf1,
    input       [11:0] dbg_spr
);

// ---------------------------------------------------------------
// Clock enables via jtframe_frac_cen.
// clk = 96 MHz master (dal PLL):
//   H6280   7.159 MHz → 1/13 (96/13 ≈ 7.38)
//   M6502   1.500 MHz → 1/64 (96/64 = 1.5 esatto)
//   YM2203  1.500 MHz → 1/64
//   YM3812  3.000 MHz → 1/32 (96/32 = 3.0 esatto)
//   OKI6295 1.024 MHz → 1/94 (96/94 ≈ 1.021)
//   pxl_cen   6 MHz  → 1/16 (96/16 = 6.0 esatto)
//   pxl2_cen 12 MHz  → 1/8  (96/8  = 12.0 esatto)
// ---------------------------------------------------------------
// --- Safe Pause: pause asincrona -> registrata SOLO al rising edge VBlank ---
// Pattern Darius2/BloodBros: pause cambia sui boundary di frame, niente
// glitch mid-frame. vbl_int e` il VBlank interno (assegnato dal modulo
// actfancer_video piu` sotto), 1=in VBlank.
wire vbl_int;
reg  vbl_prev;
reg  paused_safe_r;
always @(posedge clk) begin
    if (rst) begin
        vbl_prev       <= 1'b0;
        paused_safe_r  <= 1'b0;
    end else begin
        vbl_prev <= vbl_int;
        if (vbl_int && !vbl_prev) paused_safe_r <= pause;
    end
end
wire paused_safe = paused_safe_r;

wire [1:0] ce_h6280_w, ce_h6280b_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_cpu (
    .clk(clk), .n(7'd1), .m(7'd13), .cen(ce_h6280_w), .cenb(ce_h6280b_w)
);
wire ce_h6280 = ce_h6280_w[0] & ~paused_safe;

wire [1:0] ce_m6502_w, ce_m6502b_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_snd (
    .clk(clk), .n(7'd1), .m(7'd64), .cen(ce_m6502_w), .cenb(ce_m6502b_w)
);
wire ce_m6502 = ce_m6502_w[0] & ~paused_safe;
wire ce_opn   = ce_m6502;

wire [1:0] ce_opl_w, ce_oplb_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_opl (
    .clk(clk), .n(7'd1), .m(7'd32), .cen(ce_opl_w), .cenb(ce_oplb_w)
);
wire ce_opl = ce_opl_w[0] & ~paused_safe;

wire [1:0] ce_oki_w, ce_okib_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_oki (
    .clk(clk), .n(7'd1), .m(7'd94), .cen(ce_oki_w), .cenb(ce_okib_w)
);
wire ce_oki = ce_oki_w[0] & ~paused_safe;

wire [1:0] pxl2_cen_w, pxl2_cenb_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_pxl2 (
    .clk(clk), .n(7'd1), .m(7'd8), .cen(pxl2_cen_w), .cenb(pxl2_cenb_w)
);
wire pxl2_cen = pxl2_cen_w[0];

wire [1:0] pxl_cen_w, pxl_cenb_w;
jtframe_frac_cen #(.W(2),.WC(7)) u_cen_pxl (
    .clk(clk), .n(7'd1), .m(7'd16), .cen(pxl_cen_w), .cenb(pxl_cenb_w)
);
wire pxl_cen = pxl_cen_w[0];
assign ce_pix = pxl_cen;

// ---------------------------------------------------------------
// Wires between subsystems
// ---------------------------------------------------------------
wire        vbl_to_main;

// Main → Video
wire        pf0_mode_cs, pf0_vram_cs, pf1_mode_cs, pf1_vram_cs;
wire [12:1] pf_addr;
wire  [7:0] pf_dout, pf0_din, pf1_din;
wire        pf_we, pf_a0;

// Main → Sprite RAM
wire [10:0] spr_addr;
wire  [7:0] spr_dout, spr_din;
wire        spr_we, spr_cs, spr_buffer;

// Main → Palette
wire [10:0] pal_addr;
wire  [7:0] pal_dout, pal_din;
wire        pal_we, pal_cs;

// Main → Sound
wire  [7:0] snd_latch;
wire        snd_latch_we;

// ROM busses
wire [17:0] main_rom_addr;
wire        main_rom_cs;
wire  [7:0] main_rom_data;
wire        main_rom_ok;

wire [15:0] snd_rom_addr;
wire        snd_rom_cs;
wire  [7:0] snd_rom_data;
wire        snd_rom_ok;

wire [17:0] oki_rom_addr;
wire        oki_rom_cs;
wire  [7:0] oki_rom_data;
wire        oki_rom_ok;
wire  [7:0] oki_rom_data_bram;

wire [17:0] pf0_rom_addr;
wire        pf0_rom_cs;
wire [31:0] pf0_rom_data;
wire        pf0_rom_ok;

wire [17:0] pf1_rom_addr;
wire        pf1_rom_cs;
wire [31:0] pf1_rom_data;
wire        pf1_rom_ok;

wire [18:0] spr_rom_addr;
wire        spr_rom_cs;
wire [31:0] spr_rom_data;
wire        spr_rom_ok;

// ---------------------------------------------------------------
// Inputs (active-low to match PCB)
// ---------------------------------------------------------------
wire [7:0] p1 = ~{ joy1[7], 1'b0, joy1[5], joy1[4], joy1[3], joy1[2], joy1[1], joy1[0] };
wire [7:0] p2 = ~{ joy2[7], 1'b0, joy2[5], joy2[4], joy2[3], joy2[2], joy2[1], joy2[0] };

// SYSTEM port: {VBL_active_high, ?, ?, ?, ?, service, coin2, coin1} active-low
// In actfancer_main il bit7 di sys_q viene mappato sul vbl, qui basta passare vbl.
// (Coin/service handled by `coin` input outside this module — TODO future)

actfancer_main u_main (
    .clk        (clk),
    .ce_h6280   (ce_h6280),
    .paused_safe(paused_safe),
    .rst_n      (~rst),
    .vbl        (vbl_to_main),

    .p1         (p1),
    .p2         (p2),
    .coin       (~coin),               // top.sv `coin` is active-high → main expects active-low
    .dsw1       (dsw[7:0]),
    .dsw2       (dsw[15:8]),

    .rom_addr   (main_rom_addr),
    .rom_cs     (main_rom_cs),
    .rom_data   (main_rom_data),
    .rom_ok     (main_rom_ok),

    .pf0_mode_cs(pf0_mode_cs),
    .pf0_vram_cs(pf0_vram_cs),
    .pf1_mode_cs(pf1_mode_cs),
    .pf1_vram_cs(pf1_vram_cs),
    .pf_addr    (pf_addr),
    .pf_dout    (pf_dout),
    .pf_we      (pf_we),
    .pf_a0      (pf_a0),
    .pf0_din    (pf0_din),
    .pf1_din    (pf1_din),

    .spr_addr   (spr_addr),
    .spr_dout   (spr_dout),
    .spr_we     (spr_we),
    .spr_cs     (spr_cs),
    .spr_din    (spr_din),
    .spr_buffer (spr_buffer),

    .pal_addr   (pal_addr),
    .pal_dout   (pal_dout),
    .pal_we     (pal_we),
    .pal_din    (pal_din),
    .pal_cs     (pal_cs),

    .snd_latch    (snd_latch),
    .snd_latch_we (snd_latch_we)
);

actfancer_snd u_snd (
    .clk        (clk),
    .ce_m6502   (ce_m6502),
    .ce_opn     (ce_opn),
    .ce_opl     (ce_opl),
    .ce_oki     (ce_oki),
    .rst_n      (~rst),

    .latch_in   (snd_latch),
    .latch_we   (snd_latch_we),

    .rom_addr   (snd_rom_addr),
    .rom_cs     (snd_rom_cs),
    .rom_data   (snd_rom_data),
    .rom_ok     (snd_rom_ok),

    .oki_rom_addr(oki_rom_addr),
    .oki_rom_cs (oki_rom_cs),
    .oki_rom_data(oki_rom_data),
    .oki_rom_ok (oki_rom_ok),

    .vol_opn    (vol_opn),
    .vol_opl    (vol_opl),
    .vol_oki    (vol_oki),

    .snd_l      (aud_l),
    .snd_r      (aud_r)
);

wire [11:0] vid_rgb;
wire        hbl_int, hs_int, vs_int;  // vbl_int dichiarata in cima per Safe Pause

actfancer_video u_video (
    .clk        (clk),
    .clk_cpu    (clk),
    .pxl2_cen   (pxl2_cen),
    .pxl_cen    (pxl_cen),
    .rst        (rst),

    .pf0_mode_cs(pf0_mode_cs),
    .pf0_vram_cs(pf0_vram_cs),
    .pf1_mode_cs(pf1_mode_cs),
    .pf1_vram_cs(pf1_vram_cs),
    .pf_addr    (pf_addr),
    .pf_dout    (pf_dout),
    .pf_we      (pf_we),
    .pf_a0      (pf_a0),
    .pf0_din    (pf0_din),
    .pf1_din    (pf1_din),

    .spr_addr   (spr_addr),
    .spr_dout   (spr_dout),
    .spr_we     (spr_we),
    .spr_cs     (spr_cs),
    .spr_din    (spr_din),
    .spr_buffer (spr_buffer),

    .pal_addr   (pal_addr),
    .pal_dout   (pal_dout),
    .pal_we     (pal_we),
    .pal_cs     (pal_cs),
    .pal_din    (pal_din),

    .pf0_rom_addr(pf0_rom_addr),
    .pf0_rom_cs (pf0_rom_cs),
    .pf0_rom_data(pf0_rom_data),
    .pf0_rom_ok (pf0_rom_ok),

    .pf1_rom_addr(pf1_rom_addr),
    .pf1_rom_cs (pf1_rom_cs),
    .pf1_rom_data(pf1_rom_data),
    .pf1_rom_ok (pf1_rom_ok),

    .spr_rom_addr(spr_rom_addr),
    .spr_rom_cs (spr_rom_cs),
    .spr_rom_data(spr_rom_data),
    .spr_rom_ok (spr_rom_ok),

    .vbl        (vbl_int),
    .hbl        (hbl_int),
    .hs         (hs_int),
    .vs         (vs_int),
    .rgb        (vid_rgb),
    .dbg_dis_pf0(dbg_dis_pf0),
    .dbg_dis_pf1(dbg_dis_pf1),
    .dbg_dis_spr(dbg_dis_spr),
    .dbg_pf0    (dbg_pf0),
    .dbg_pf1    (dbg_pf1),
    .dbg_spr    (dbg_spr)
);

assign vbl_to_main = vbl_int;

// xBGR_444 → 8:8:8 (replicate nibble)
assign vga_r  = { vid_rgb[3:0], vid_rgb[3:0] };
assign vga_g  = { vid_rgb[7:4], vid_rgb[7:4] };
assign vga_b  = { vid_rgb[11:8], vid_rgb[11:8] };
assign vga_hs = hs_int;
assign vga_vs = vs_int;
assign vga_hb = hbl_int;
assign vga_vb = vbl_int;

// ---------------------------------------------------------------
// CPU ROMs in BRAM (popolate via ioctl_download dalla MRA).
// Pattern ChinaGate: dl_* segnali generati esternamente.
//   maincpu  : 192KB @ ioctl 0x000000-0x02FFFF
//   audiocpu :  64KB @ ioctl 0x030000-0x03FFFF
// ---------------------------------------------------------------
wire        dl_active = ioctl_download && (ioctl_index == 16'd0);

wire [25:0] main_dl_off = ioctl_addr - 25'h000000;
wire        main_dl_wr  = dl_active && ioctl_wr
                          && (ioctl_addr < 25'h030000);
wire [17:0] main_dl_addr = main_dl_off[17:0];

actfancer_rom_bram #(.AW(18)) u_main_rom (
    .clk        (clk),
    .dl_wr      (main_dl_wr),
    .dl_addr    (main_dl_addr),
    .dl_data    (ioctl_dout),
    .cpu_addr   (main_rom_addr),
    .cpu_data   (main_rom_data)
);

wire [25:0] snd_dl_off = ioctl_addr - 25'h030000;
wire        snd_dl_wr  = dl_active && ioctl_wr
                         && (ioctl_addr >= 25'h030000)
                         && (ioctl_addr < 25'h040000);
wire [15:0] snd_dl_addr = snd_dl_off[15:0];

actfancer_rom_bram #(.AW(16)) u_snd_rom (
    .clk        (clk),
    .dl_wr      (snd_dl_wr),
    .dl_addr    (snd_dl_addr),
    .dl_data    (ioctl_dout),
    .cpu_addr   (snd_rom_addr),
    .cpu_data   (snd_rom_data)
);

// OKI ROM in BRAM 64KB @ ioctl 0x100000-0x10FFFF.
// MAME ROM_REGION 256KB ma file "18" e` solo 64KB (vedi actfancr.cpp:471).
// Spostato da SDRAM bridge per evitare latency variabile / cache miss:
// jt6295 con BRAM ha rom_ok=1 sempre e oki_rom_data deterministico a 1 ciclo.
wire [25:0] oki_dl_off = ioctl_addr - 25'h100000;
wire        oki_dl_wr  = dl_active && ioctl_wr
                         && (ioctl_addr >= 25'h100000)
                         && (ioctl_addr < 25'h110000);
wire [15:0] oki_dl_addr = oki_dl_off[15:0];

actfancer_rom_bram #(.AW(16)) u_oki_rom (
    .clk        (clk),
    .dl_wr      (oki_dl_wr),
    .dl_addr    (oki_dl_addr),
    .dl_data    (ioctl_dout),
    .cpu_addr   (oki_rom_addr[15:0]),
    .cpu_data   (oki_rom_data_bram)
);

assign main_rom_ok = 1'b1;
assign snd_rom_ok  = 1'b1;

// Tutte le gfx + oki via SDRAM bridge
assign sdr_pf0_addr  = pf0_rom_addr;
assign sdr_pf0_cs    = pf0_rom_cs;
assign pf0_rom_data  = sdr_pf0_data;
assign pf0_rom_ok    = sdr_pf0_ok;

assign sdr_pf1_addr  = pf1_rom_addr;
assign sdr_pf1_cs    = pf1_rom_cs;
assign pf1_rom_data  = sdr_pf1_data;
assign pf1_rom_ok    = sdr_pf1_ok;

assign sdr_spr_addr  = spr_rom_addr;
assign sdr_spr_cs    = spr_rom_cs;
assign spr_rom_data  = sdr_spr_data;
assign spr_rom_ok    = sdr_spr_ok;

// OKI ROM ora in BRAM locale (vedi sopra u_oki_rom). SDRAM porta liberata.
assign sdr_oki_addr  = 18'd0;
assign sdr_oki_cs    = 1'b0;
assign oki_rom_data  = oki_rom_data_bram;
assign oki_rom_ok    = 1'b1;  // BRAM 1-ck read latency, sempre pronta

endmodule
